# _config.yml (minimal example)
title: "Tyler Eck — CV"
description: "Cloud & Security Engineer • Big Data Security"
url: "https://tylereck81.github.io" 

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Tyler Eck"
  avatar: "/assets/images/avatar.jpg"
  bio: "Erasmus Mundus SECCLO • Big Data Security @ EURECOM"
  location: "Antibes, France"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:tyler.eck@eurecom.fr"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Tylereck81"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tylereck81/"

