# _config.yml (minimal example)
title: "Tyler Eck — CV"
description: "Cloud & Security Engineer • Big Data Security"
url: "https://tylereck-cv.io"   # if using username.github.io

remote_theme: "mmistakes/minimal-mistakes"

# Optional: turn off blog pagination on the home page if you want a simple front
paginate: 0

author:
  name: "Tyler Eck"
  avatar: "/assets/images/avatar.jpg"  # add this file later if you want
  bio: "Erasmus Mundus SECCLO • Big Data Security @ EURECOM"
  location: "Antibes, France"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "tyler.eck@eurecom.fr"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Tylereck81"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tylereck81/"

